#!/usr/bin/env bash
# Source: https://github.com/amulya-labs/ai-dev-foundry
# License: MIT (https://opensource.org/licenses/MIT)
#
# review-stats-helper.sh -- Wrapper around review-stats.py for CI/CD usage.
# Fetches stats, checks thresholds, and optionally posts a summary to a PR.

set -euo pipefail

# ---------------------------------------------------------------------------
# Defaults
# ---------------------------------------------------------------------------
REPO="${GITHUB_REPOSITORY:-}"
DAYS="${STATS_DAYS:-30}"
CRITICAL_THRESHOLD="${CRITICAL_THRESHOLD:-0}"
HIGH_THRESHOLD="${HIGH_THRESHOLD:-5}"
OUTPUT_FORMAT="${OUTPUT_FORMAT:-table}"
POST_TO_PR="${POST_TO_PR:-0}"
PR_NUMBER="${PR_NUMBER:-}"

# ---------------------------------------------------------------------------
# Functions
# ---------------------------------------------------------------------------

usage() {
  cat <<EOF
Usage: $0 [OPTIONS]

Options:
  --repo OWNER/REPO     GitHub repository (default: \$GITHUB_REPOSITORY)
  --days N              Days to look back (default: 30)
  --critical-threshold  Max critical findings before failing (default: 0)
  --high-threshold      Max high findings before failing (default: 5)
  --format json|table   Output format (default: table)
  --post-to-pr N        Post summary as comment on PR #N
  --help                Show this help message

Environment variables:
  GITHUB_REPOSITORY     Default repository
  STATS_DAYS            Default days lookback
  CRITICAL_THRESHOLD    Max critical findings
  HIGH_THRESHOLD        Max high findings
  GH_TOKEN              GitHub token for posting comments
EOF
}

die() {
  echo "ERROR: $*" >&2
  exit 1
}

check_dependencies() {
  command -v python3 >/dev/null 2>&1 || die "python3 is required"
  command -v gh >/dev/null 2>&1 || die "gh CLI is required"
  command -v jq >/dev/null 2>&1 || die "jq is required"
}

run_stats() {
  local repo="$1" days="$2" fmt="$3"

  python3 "$(dirname "$0")/review-stats.py" \
    --repo "$repo" \
    --days "$days" \
    --format "$fmt"
}

check_thresholds() {
  local stats_json="$1"
  local critical high
  local exit_code=0

  critical=$(echo "$stats_json" | jq -r '.severity_counts.Critical // 0')
  high=$(echo "$stats_json" | jq -r '.severity_counts.High // 0')

  if [ "$critical" -gt "$CRITICAL_THRESHOLD" ]; then
    echo "FAIL: $critical critical findings exceed threshold of $CRITICAL_THRESHOLD" >&2
    exit_code=1
  fi

  if [ "$high" -gt "$HIGH_THRESHOLD" ]; then
    echo "FAIL: $high high findings exceed threshold of $HIGH_THRESHOLD" >&2
    exit_code=1
  fi

  return $exit_code
}

post_comment() {
  local repo="$1" pr="$2" body="$3"

  if [ -z "$pr" ]; then
    echo "WARNING: No PR number specified, skipping comment" >&2
    return 0
  fi

  echo "$body" | gh pr comment "$pr" --repo "$repo" --body-file -
}

# ---------------------------------------------------------------------------
# Argument parsing
# ---------------------------------------------------------------------------

while [ $# -gt 0 ]; do
  case "$1" in
    --repo) REPO="$2"; shift 2 ;;
    --days) DAYS="$2"; shift 2 ;;
    --critical-threshold) CRITICAL_THRESHOLD="$2"; shift 2 ;;
    --high-threshold) HIGH_THRESHOLD="$2"; shift 2 ;;
    --format) OUTPUT_FORMAT="$2"; shift 2 ;;
    --post-to-pr) POST_TO_PR=1; PR_NUMBER="$2"; shift 2 ;;
    --help) usage; exit 0 ;;
    *) die "Unknown option: $1" ;;
  esac
done

# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

check_dependencies

[ -n "$REPO" ] || die "--repo is required (or set GITHUB_REPOSITORY)"

echo "Collecting review stats for $REPO (last $DAYS days)..." >&2

# Always get JSON for threshold checking
STATS_JSON=$(run_stats "$REPO" "$DAYS" "json")

if [ "$OUTPUT_FORMAT" = "table" ]; then
  # Re-run with table format for display
  run_stats "$REPO" "$DAYS" "table"
else
  echo "$STATS_JSON"
fi

# Check thresholds
THRESHOLD_RESULT=0
check_thresholds "$STATS_JSON" || THRESHOLD_RESULT=$?

# Post to PR if requested
if [ "$POST_TO_PR" = "1" ] && [ -n "$PR_NUMBER" ]; then
  TOTAL=$(echo "$STATS_JSON" | jq -r '.total_findings')
  REVIEWS=$(echo "$STATS_JSON" | jq -r '.total_reviews')
  COMMENT_BODY="## Review Statistics (last $DAYS days)

| Metric | Value |
|--------|-------|
| Reviews | $REVIEWS |
| Findings | $TOTAL |
| Critical | $(echo "$STATS_JSON" | jq -r '.severity_counts.Critical // 0') |
| High | $(echo "$STATS_JSON" | jq -r '.severity_counts.High // 0') |
| Medium | $(echo "$STATS_JSON" | jq -r '.severity_counts.Medium // 0') |
| Low | $(echo "$STATS_JSON" | jq -r '.severity_counts.Low // 0') |

_Generated by review-stats_"

  post_comment "$REPO" "$PR_NUMBER" "$COMMENT_BODY"
  echo "Posted stats comment to PR #$PR_NUMBER" >&2
fi

exit "$THRESHOLD_RESULT"
